name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: stefan-work  # Replace with your GCP project ID

    - name: Build Maven
      run: mvn clean install

    - name: Build Docker image
      run: |
        docker build -t stefanmita1234/apache-beam-dataflow:${{ github.sha }} .

    - name: Push Docker image
      run: |
        echo "Pushing image to GCR..."
        docker push stefanmita1234/apache-beam-dataflow:${{ github.sha }}
